/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CompanyMapRouteImport } from './routes/company-map'
import { Route as CompanyOsRouteImport } from './routes/company-os'
import { Route as JarvisRouteImport } from './routes/jarvis'
import { Route as KpiRouteImport } from './routes/kpi'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as EmployeesCodeRouteImport } from './routes/employees.$code'
import { Route as ApiVoiceSpeakRouteImport } from './routes/api/voice.speak'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice.transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyMapRoute = CompanyMapRouteImport.update({
  id: '/company-map',
  path: '/company-map',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyOsRoute = CompanyOsRouteImport.update({
  id: '/company-os',
  path: '/company-os',
  getParentRoute: () => rootRouteImport,
} as any)
const JarvisRoute = JarvisRouteImport.update({
  id: '/jarvis',
  path: '/jarvis',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiRoute = KpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesCodeRoute = EmployeesCodeRouteImport.update({
  id: '/employees/$code',
  path: '/employees/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSpeakRoute = ApiVoiceSpeakRouteImport.update({
  id: '/api/voice/speak',
  path: '/api/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/company-map': typeof CompanyMapRoute
  '/company-os': typeof CompanyOsRoute
  '/jarvis': typeof JarvisRoute
  '/kpi': typeof KpiRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/workflows': typeof WorkflowsRoute
  '/api/chat': typeof ApiChatRoute
  '/employees/$code': typeof EmployeesCodeRoute
  '/employees/': typeof EmployeesIndexRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/company-map': typeof CompanyMapRoute
  '/company-os': typeof CompanyOsRoute
  '/jarvis': typeof JarvisRoute
  '/kpi': typeof KpiRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/workflows': typeof WorkflowsRoute
  '/api/chat': typeof ApiChatRoute
  '/employees/$code': typeof EmployeesCodeRoute
  '/employees': typeof EmployeesIndexRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/company-map': typeof CompanyMapRoute
  '/company-os': typeof CompanyOsRoute
  '/jarvis': typeof JarvisRoute
  '/kpi': typeof KpiRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/workflows': typeof WorkflowsRoute
  '/api/chat': typeof ApiChatRoute
  '/employees/$code': typeof EmployeesCodeRoute
  '/employees/': typeof EmployeesIndexRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/audit'
    | '/calendar'
    | '/company-map'
    | '/company-os'
    | '/jarvis'
    | '/kpi'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/tasks'
    | '/workflows'
    | '/api/chat'
    | '/employees/$code'
    | '/employees/'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/audit'
    | '/calendar'
    | '/company-map'
    | '/company-os'
    | '/jarvis'
    | '/kpi'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/tasks'
    | '/workflows'
    | '/api/chat'
    | '/employees/$code'
    | '/employees'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/audit'
    | '/calendar'
    | '/company-map'
    | '/company-os'
    | '/jarvis'
    | '/kpi'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/tasks'
    | '/workflows'
    | '/api/chat'
    | '/employees/$code'
    | '/employees/'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  CalendarRoute: typeof CalendarRoute
  CompanyMapRoute: typeof CompanyMapRoute
  CompanyOsRoute: typeof CompanyOsRoute
  JarvisRoute: typeof JarvisRoute
  KpiRoute: typeof KpiRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  RevenueRoute: typeof RevenueRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ApiChatRoute: typeof ApiChatRoute
  EmployeesCodeRoute: typeof EmployeesCodeRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  ApiVoiceSpeakRoute: typeof ApiVoiceSpeakRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-map': {
      id: '/company-map'
      path: '/company-map'
      fullPath: '/company-map'
      preLoaderRoute: typeof CompanyMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-os': {
      id: '/company-os'
      path: '/company-os'
      fullPath: '/company-os'
      preLoaderRoute: typeof CompanyOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jarvis': {
      id: '/jarvis'
      path: '/jarvis'
      fullPath: '/jarvis'
      preLoaderRoute: typeof JarvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi': {
      id: '/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof KpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$code': {
      id: '/employees/$code'
      path: '/employees/$code'
      fullPath: '/employees/$code'
      preLoaderRoute: typeof EmployeesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/speak': {
      id: '/api/voice/speak'
      path: '/api/voice/speak'
      fullPath: '/api/voice/speak'
      preLoaderRoute: typeof ApiVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  CalendarRoute: CalendarRoute,
  CompanyMapRoute: CompanyMapRoute,
  CompanyOsRoute: CompanyOsRoute,
  JarvisRoute: JarvisRoute,
  KpiRoute: KpiRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  RevenueRoute: RevenueRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  WorkflowsRoute: WorkflowsRoute,
  ApiChatRoute: ApiChatRoute,
  EmployeesCodeRoute: EmployeesCodeRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  ApiVoiceSpeakRoute: ApiVoiceSpeakRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
